AWSTemplateFormatVersion: '2010-09-09'
Description: 'A serverless ETL pipeline for storing and processing visitor gender
  hits couple with a gender service to predict a visitor''s gender by ID.

  '
Outputs:
  S3BucketNameKinesisFirehose:
    Description: S3 bucket to store the streaming data from Kinesis Firehose
    Value:
      Fn::GetAtt:
      - S3BucketStoreFirehoseStream
      - Arn
Resources:
  S3BucketStoreFirehoseStream:
    Properties:
      AccessControl: Private
      BucketName: case-study-kinesis-firehose-stream
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
