AWSTemplateFormatVersion: '2010-09-09'
Description: 'A serverless ETL pipeline for storing and processing visitor gender
  hits couple with a gender service to predict a visitor''s gender by ID.

  '
Outputs:
  KinesisFirehoseDeliverStream:
    Description: Kinesis Firehose Delivery Stream ARN
    Value:
      Fn::GetAtt:
      - KinesisFirehoseDeliveryStream
      - Arn
  S3BucketNameKinesisFirehose:
    Description: S3 bucket to store the streaming data from Kinesis Firehose
    Value:
      Fn::GetAtt:
      - S3BucketStoreFirehoseStream
      - Arn
Resources:
  KinesisDeliveryPolicy:
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - s3:AbortMultipartUpload
          - s3:GetBucketLocation
          - s3:GetObject
          - s3:ListBucket
          - s3:ListBucketMultipartUploads
          - s3:PutObject
          Effect: Allow
          Resource:
          - Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: S3BucketStoreFirehoseStream
          - Fn::Join:
            - ''
            - - 'arn:aws:s3:::'
              - Ref: S3BucketStoreFirehoseStream
              - '*'
        Version: 2012-10-17
      PolicyName: firehose_delivery_policy
      Roles:
      - Ref: KinesisDeliveryRole
    Type: AWS::IAM::Policy
  KinesisDeliveryRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: sts:AssumeRole
          Condition:
            StringEquals:
              sts:ExternalId:
                Ref: AWS::AccountId
          Effect: Allow
          Principal:
            Service: firehose.amazonaws.com
          Sid: ''
        Version: 2012-10-17
    Type: AWS::IAM::Role
  KinesisFirehoseDeliveryStream:
    DependsOn:
    - KinesisDeliveryPolicy
    Properties:
      ExtendedS3DestinationConfiguration:
        BucketARN:
          Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: S3BucketStoreFirehoseStream
        BufferingHints:
          IntervalInSeconds: '60'
          SizeInMBs: '50'
        CompressionFormat: UNCOMPRESSED
        Prefix: firehose/
        RoleARN:
          Fn::GetAtt:
          - KinesisDeliveryRole
          - Arn
    Type: AWS::KinesisFirehose::DeliveryStream
  S3BucketStoreFirehoseStream:
    Properties:
      AccessControl: Private
      BucketName: case-study-kinesis-firehose-stream
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
