AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    A serverless ETL pipeline for storing and processing
    visitor gender hits couple with a gender service to
    predict a visitor's gender by ID.


Resources:

    S3BucketStoreFirehoseStream:
        Type: 'AWS::S3::Bucket'
        #DeletionPolicy: Retain
        Properties:
            AccessControl: Private
            BucketName: case-study-kinesis-firehose-stream

Outputs:

    S3BucketNameKinesisFirehose:
        Description: "S3 bucket to store the streaming data from Kinesis Firehose"
        Value: !GetAtt S3BucketStoreFirehoseStream.Arn

